# no pods for main target yet

use_frameworks!

target 'Tomighty' do
  pod 'SwiftyTimer'
end

# this workaround should not be necessary with cocoapods 1.1.1
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

target :TomightyTests do
	pod 'OCMockito', '~> 3.0'
end
